version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    groups:
      cloudflare:
        patterns:
          - "@cloudflare/workers-types"
          - "wrangler"
        update-types:
          - minor
          - patch
    reviewers:
      - toshimaru
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    reviewers:
      - toshimaru
